image: amazon/aws-sam-cli-build-image-python3.8

before_script:
  - yum install -y jq

stages:
  - test
  - build
  - staging
  - staging-integration-test
  - prod

unit-test:
  stage: test
  only:
    - mainline
    - /^feature-*$/
  script: |
    pip install pytest
    pip install -r ${CI_PROJECT_DIR}/hello_world/requirements.txt
    python -m pytest tests/unit

build-and-deploy-feature:
  stage: build
  only:
    - /^feature-*$/
  script: |
    . cicd/assume-role.sh $AWS_ACCESS_KEY_ID \
                          $AWS_SECRET_ACCESS_KEY \
                          eu-west-1 \
                          arn:aws:iam::288362329835:role/cicd-deployment-resources-DeployerRole-BT7FWOJ0GX1D \
                          feature-deployment
    sam build
    sam deploy --stack-name features-${CI_COMMIT_REF_NAME}-cfn-stack \
               --capabilities CAPABILITY_IAM \
               --region eu-west-1 \
               --s3-bucket application-artifacts-eu-west-1-380564965876 \
               --no-fail-on-empty-changeset \
               --role-arn arn:aws:iam::288362329835:role/cicd-deployment-resources-CFNDeploymentRole-9JSTGWWC5Y27
build:
  stage: build
  only:
    - mainline
  script: |
    sam build

    sam package \
          --s3-bucket application-artifacts-eu-west-1-380564965876 \
          --region eu-west-1 \
          --output-template-file packaged-eu-west-1.yaml

    sam package \
           --s3-bucket application-artifacts-us-east-2-380564965876 \
           --region us-east-2 \
           --output-template-file packaged-us-east-2.yaml
  artifacts:
    paths:
      - packaged-eu-west-1.yaml
      - packaged-us-east-2.yaml
    expire_in: 1 year

deploy-staging:
  stage: staging
  only:
    - mainline
  script: |
    . cicd/assume-role.sh $AWS_ACCESS_KEY_ID \
                          $AWS_SECRET_ACCESS_KEY \
                          eu-west-1 \
                          arn:aws:iam::288362329835:role/cicd-deployment-resources-DeployerRole-BT7FWOJ0GX1D \
                          staging-deployment
    sam deploy --stack-name staging-cfn-stack \
               --template packaged-eu-west-1.yaml \
               --capabilities CAPABILITY_IAM \
               --region eu-west-1 \
               --s3-bucket application-artifacts-eu-west-1-380564965876 \
               --no-fail-on-empty-changeset \
               --role-arn arn:aws:iam::288362329835:role/cicd-deployment-resources-CFNDeploymentRole-9JSTGWWC5Y27

staging-integration-test:
  stage: staging-integration-test
  only:
    - mainline
  script: |
    pip install -r ${CI_PROJECT_DIR}/tests/integration/requirements.txt
    . cicd/assume-role.sh $AWS_ACCESS_KEY_ID \
                          $AWS_SECRET_ACCESS_KEY \
                          eu-west-1 \
                          arn:aws:iam::288362329835:role/cicd-deployment-resources-DeployerRole-BT7FWOJ0GX1D \
                          staging-deployment
    apiDomain=$(aws cloudformation describe-stack-resource \
                                   --logical-resource-id ServerlessRestApi \
                                   --stack-name staging-cfn-stack \
                                   --region eu-west-1 \
                                   --query 'StackResourceDetail.PhysicalResourceId' \
                                   --output text)
    API_DOMAIN=$apiDomain REGION=eu-west-1 python -m unittest discover -s tests/integration

deploy-prod:
  stage: prod
  only:
    - mainline
  script: |
    . cicd/assume-role.sh $AWS_ACCESS_KEY_ID \
                          $AWS_SECRET_ACCESS_KEY \
                          us-east-2 \
                          arn:aws:iam::074570342695:role/cicd-deployment-resources-DeployerRole-1UOJFUSTWWKCD \
                          prod-deployment
    sam deploy --stack-name prod-cfn-stack \
               --template packaged-us-east-2.yaml \
               --capabilities CAPABILITY_IAM \
               --region us-east-2 \
               --s3-bucket application-artifacts-us-east-2-380564965876 \
               --no-fail-on-empty-changeset \
               --role-arn arn:aws:iam::074570342695:role/cicd-deployment-resources-CFNDeploymentRole-1DCYC13CPLRQB
