AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  CicdPlatformTokenSecretKeyArn:
    Type: String
  CicdPlatformRestAPI:
    Type: String
Resources:
  Deployer:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: AssumeRoles
          PolicyDocument: |
            {
                "Version": "2012-10-17",
                "Statement": [{
                    "Effect": "Allow",
                    "Action": ["sts:AssumeRole"],
                    "Resource": "*"
                }]
            }
  DeployerCredentialRotationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../
      Handler: iam_key_rotation.handler
      Runtime: python3.8
      Environment:
        Variables:
          DeployerUserName: !Ref Deployer
          CicdPlatformTokenSecretKeyArn: !Ref CicdPlatformTokenSecretKeyArn
          CicdPlatformRestAPI: !Ref CicdPlatformRestAPI
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - iam:ListAccessKeys
                - iam:CreateAccessKey
                - iam:DeleteAccessKey
              Resource: !GetAtt Deployer.Arn
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Ref CicdPlatformTokenSecretKeyArn
      Events:
        schedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)



Outputs:
  Deployer:
    Description: ARN of the IAM User(Deployer)
    Value: !GetAtt Deployer.Arn